name: Install CLI dependencies
description: Install minimal CLI-only dependencies for building the CLI binary
runs:
  using: composite
  steps:
    - name: Install bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.2.22
    - name: Install deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: v2.5.2
    - name: Install CLI dependencies
      shell: bash
      run: |
        cd cli
        bun install --production
