name: Install dependencies
description: Install project tools/dependencies
runs:
  using: composite
  steps:
    - name: Install bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.2.22
        cache: bun
    - name: Install deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: v2.5.2
    - name: Install dependencies
      shell: bash
      run: bun install
