/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_architecturejs_free(a: number, b: number): void;
export function architecturejs_from_json(a: number, b: number): Array;
export function architecturejs_toString(a: number): Array;
export function architecturejs_compile(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number): Array;
export function architecturejs_schema(): Array;
export function __wbg_compiledcodejs_free(a: number, b: number): void;
export function __wbg_get_compiledcodejs_instructions(a: number): Array;
export function __wbg_get_compiledcodejs_data(a: number): Array;
export function __wbg_get_compiledcodejs_label_table(a: number): Array;
export function compiledcodejs_toString(a: number): Array;
export function __wbg_labeljs_free(a: number, b: number): void;
export function __wbg_get_labeljs_address(a: number): number;
export function __wbg_set_labeljs_address(a: number, b: number): void;
export function __wbg_get_labeljs_global(a: number): number;
export function __wbg_set_labeljs_global(a: number, b: number): void;
export function __wbg_instructionjs_free(a: number, b: number): void;
export function __wbg_get_instructionjs_address(a: number): Array;
export function __wbg_set_instructionjs_address(a: number, b: number, c: number): void;
export function __wbg_get_instructionjs_labels(a: number): Array;
export function __wbg_set_instructionjs_labels(a: number, b: number, c: number): void;
export function __wbg_get_instructionjs_loaded(a: number): Array;
export function __wbg_set_instructionjs_loaded(a: number, b: number, c: number): void;
export function __wbg_get_instructionjs_binary(a: number): Array;
export function __wbg_set_instructionjs_binary(a: number, b: number, c: number): void;
export function __wbg_get_instructionjs_user(a: number): Array;
export function __wbg_set_instructionjs_user(a: number, b: number, c: number): void;
export function __wbg_datajs_free(a: number, b: number): void;
export function datajs_address(a: number): number;
export function datajs_labels(a: number): Array;
export function datajs_value(a: number, b: number): Array;
export function datajs_type(a: number): Array;
export function datajs_data_category(a: number): number;
export function datajs_size(a: number): number;
export function __wbg_set_labeljs_name(a: number, b: number, c: number): void;
export function __wbg_get_labeljs_name(a: number): Array;
export function __wbindgen_export_0(a: number, b: number): number;
export function __wbindgen_export_1(a: number, b: number, c: number, d: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function __wbindgen_export_3(a: number): void;
export function __wbindgen_export_4(a: number, b: number, c: number): void;
export function __wbindgen_export_5(a: number, b: number): void;
export function __wbindgen_export_6(): number;
export function __wbindgen_export_7(a: number): void;
export function __wbindgen_start(): void;
