/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_architecturejs_free: (a: number, b: number) => void;
export const architecturejs_from_json: (a: number, b: number) => [number, number, number];
export const architecturejs_toString: (a: number) => [number, number];
export const architecturejs_compile: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number, number];
export const architecturejs_schema: () => [number, number];
export const __wbg_compiledcodejs_free: (a: number, b: number) => void;
export const __wbg_get_compiledcodejs_instructions: (a: number) => [number, number];
export const __wbg_get_compiledcodejs_data: (a: number) => [number, number];
export const __wbg_get_compiledcodejs_label_table: (a: number) => [number, number];
export const compiledcodejs_toString: (a: number) => [number, number];
export const __wbg_labeljs_free: (a: number, b: number) => void;
export const __wbg_get_labeljs_name: (a: number) => [number, number];
export const __wbg_get_labeljs_address: (a: number) => any;
export const __wbg_set_labeljs_address: (a: number, b: any) => void;
export const __wbg_get_labeljs_global: (a: number) => number;
export const __wbg_set_labeljs_global: (a: number, b: number) => void;
export const __wbg_instructionjs_free: (a: number, b: number) => void;
export const __wbg_get_instructionjs_address: (a: number) => [number, number];
export const __wbg_set_instructionjs_address: (a: number, b: number, c: number) => void;
export const __wbg_get_instructionjs_labels: (a: number) => [number, number];
export const __wbg_set_instructionjs_labels: (a: number, b: number, c: number) => void;
export const __wbg_get_instructionjs_loaded: (a: number) => [number, number];
export const __wbg_set_instructionjs_loaded: (a: number, b: number, c: number) => void;
export const __wbg_get_instructionjs_binary: (a: number) => [number, number];
export const __wbg_set_instructionjs_binary: (a: number, b: number, c: number) => void;
export const __wbg_get_instructionjs_user: (a: number) => [number, number];
export const __wbg_set_instructionjs_user: (a: number, b: number, c: number) => void;
export const __wbg_datajs_free: (a: number, b: number) => void;
export const datajs_address: (a: number) => any;
export const datajs_labels: (a: number) => [number, number];
export const datajs_value: (a: number, b: number) => [number, number];
export const datajs_type: (a: number) => [number, number];
export const datajs_data_category: (a: number) => number;
export const datajs_size: (a: number) => any;
export const __wbg_set_labeljs_name: (a: number, b: number, c: number) => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_2: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_start: () => void;
